In [1]:
import pandas as pd
import numpy as np
import time

In [2]:
historical_df = pd.read_csv('BTC_Price_2013_2019.csv')
historical_df.head()

              timestamp     open    close   Δprice volume
0  2013-04-28T00:00:00Z  $133.77  $139.68   +4.42%    NaN
1  2013-04-29T00:00:00Z  $139.68  $142.26   +1.85%    NaN
2  2013-04-30T00:00:00Z  $142.26  $128.14   -9.93%    NaN
3  2013-05-01T00:00:00Z  $128.14  $111.36  -13.10%    NaN
4  2013-05-02T00:00:00Z  $111.36   $93.40  -16.13%    NaN

In [3]:
historical_df['date'] = pd.to_datetime(historical_df['timestamp'])
historical_df['date'] = historical_df['date'].dt.date
historical_df = historical_df[["date", "open", "close", "Δprice", "volume"]]
historical_df.head()

         date     open    close   Δprice volume
0  2013-04-28  $133.77  $139.68   +4.42%    NaN
1  2013-04-29  $139.68  $142.26   +1.85%    NaN
2  2013-04-30  $142.26  $128.14   -9.93%    NaN
3  2013-05-01  $128.14  $111.36  -13.10%    NaN
4  2013-05-02  $111.36   $93.40  -16.13%    NaN

In [4]:
sentiment_df = pd.read_csv('articles_with_sentiment.csv')
sentiment_df = sentiment_df[["date", "headline", "abstract", "sentiment", "url"]]
sentiment_df.head()

,date,headline,abstract,sentiment,url
0,2019-08-14 16:22:02,Trade Tensions and a Weaker Yuan Drive Chinese...,Trade tensions between the United States and C...,0.894214,https://www.nytimes.com/reuters/2019/08/14/bus...
1,2019-08-14 10:33:39,Barclays Ends Partnership With Cryptocurrency ...,Barclays is no longer providing banking servic...,0.695652,https://www.nytimes.com/reuters/2019/08/14/bus...
2,2019-08-14 10:00:04,"They Stole Your Files, You Don’t Have to Pay t...",The F.B.I. should follow the example of Europe...,0.520264,https://www.nytimes.com/2019/08/14/opinion/ran...
3,2019-08-13 06:06:40,European Blockchain Company Bitfury Launches A...,"European blockchain company The Bitfury Group,...",0.443362,https://www.nytimes.com/reuters/2019/08/13/bus...
4,2019-08-12 12:15:47,"IBM, India's Tata Join U.S. Tech Platform's Go...",International Business Machines Corp and Tata ...,0.983823,https://www.nytimes.com/reuters/2019/08/12/bus...

In [5]:
sentiment_df['date'] = pd.to_datetime(sentiment_df['date'])
sentiment_df['date'] = sentiment_df['date'].dt.date
sentiment_df.head()

,date,headline,abstract,sentiment,url
0,2019-08-14,Trade Tensions and a Weaker Yuan Drive Chinese...,Trade tensions between the United States and C...,0.894214,https://www.nytimes.com/reuters/2019/08/14/bus...
1,2019-08-14,Barclays Ends Partnership With Cryptocurrency ...,Barclays is no longer providing banking servic...,0.695652,https://www.nytimes.com/reuters/2019/08/14/bus...
2,2019-08-14,"They Stole Your Files, You Don’t Have to Pay t...",The F.B.I. should follow the example of Europe...,0.520264,https://www.nytimes.com/2019/08/14/opinion/ran...
3,2019-08-13,European Blockchain Company Bitfury Launches A...,"European blockchain company The Bitfury Group,...",0.443362,https://www.nytimes.com/reuters/2019/08/13/bus...
4,2019-08-12,"IBM, India's Tata Join U.S. Tech Platform's Go...",International Business Machines Corp and Tata ...,0.983823,https://www.nytimes.com/reuters/2019/08/12/bus...

In [11]:
merged_df = sentiment_df.merge(how='left', right=historical_df, left_on='date', right_on='date')
merged_df

,date,headline,abstract,sentiment,url,open,close,Δprice,volume
0,2019-08-14,Trade Tensions and a Weaker Yuan Drive Chinese...,Trade tensions between the United States and C...,0.894214,https://www.nytimes.com/reuters/2019/08/14/bus...,"$10,482.86","$10,056.65",-4.07%,"$16,274,403,510.00"
1,2019-08-14,Barclays Ends Partnership With Cryptocurrency ...,Barclays is no longer providing banking servic...,0.695652,https://www.nytimes.com/reuters/2019/08/14/bus...,"$10,482.86","$10,056.65",-4.07%,"$16,274,403,510.00"
2,2019-08-14,"They Stole Your Files, You Don’t Have to Pay t...",The F.B.I. should follow the example of Europe...,0.520264,https://www.nytimes.com/2019/08/14/opinion/ran...,"$10,482.86","$10,056.65",-4.07%,"$16,274,403,510.00"
3,2019-08-13,European Blockchain Company Bitfury Launches A...,"European blockchain company The Bitfury Group,...",0.443362,https://www.nytimes.com/reuters/2019/08/13/bus...,"$11,176.89","$10,482.86",-6.21%,"$12,541,372,392.00"
4,2019-08-12,"IBM, India's Tata Join U.S. Tech Platform's Go...",International Business Machines Corp and Tata ...,0.983823,https://www.nytimes.com/reuters/2019/08/12/bus...,"$11,415.22","$11,176.89",-2.09%,"$12,498,103,202.00"
5,2019-08-12,Take Five: The Devil's in the Data,LONDON (Reuters) -,0.234622,https://www.nytimes.com/reuters/2019/08/12/bus...,"$11,415.22","$11,176.89",-2.09%,"$12,498,103,202.00"
6,2019-08-09,Take Five: The Devil's in the Data,1/ READY FOR A SCARY EURO ZONE GDP SHOW?,0.234622,https://www.nytimes.com/reuters/2019/08/09/bus...,"$11,842.00","$11,618.78",-1.88%,"$16,859,879,733.00"
7,2019-08-09,Take Five: The Devil's in the Data,1/ READY FOR A SCARY EURO ZONE GDP SHOW?,0.234622,https://www.nytimes.com/reuters/2019/08/09/bus...,"$11,842.00","$11,618.78",-1.88%,"$16,859,879,733.00"
8,2019-08-07,DealBook Briefing: China vs. U.S. Could Be a L...,"Its economy struggling, China may try to infli...",0.621441,https://www.nytimes.com/2019/08/07/business/de...,"$11,716.10","$11,816.52",+0.86%,"$19,259,055,362.00"
9,2019-08-07,Bitcoin as a Safe Haven? More a Speculative Be...,Bitcoin's recent gains as stocks plummeted on ...,0.895292,https://www.nytimes.com/reuters/2019/08/06/bus...,"$11,716.10","$11,816.52",+0.86%,"$19,259,055,362.00"
10,2019-08-05,UN Report: North Korea Cyber Experts Raised Up...,A panel monitoring U.N. sanctions says North K...,0.222053,https://www.nytimes.com/aponline/2019/08/05/wo...,"$11,662.41","$11,770.45",+0.93%,"$18,023,909,760.00"
11,2019-08-02,Apple Card Will Not Allow Purchase of Cryptocu...,The Apple Inc credit card being launched with ...,0.620720,https://www.nytimes.com/reuters/2019/08/02/bus...,"$10,489.98","$10,602.21",+1.07%,"$14,990,887,366.00"
12,2019-08-02,Vermont Man Gets 5 Years for Dark Web Drug Dea...,A Vermont man was sentenced to five years in f...,0.692173,https://www.nytimes.com/aponline/2019/08/02/us...,"$10,489.98","$10,602.21",+1.07%,"$14,990,887,366.00"
13,2019-07-28,Hackers’ Latest Target: School Districts,Schools handle a lot of personal data and may ...,0.556016,https://www.nytimes.com/2019/07/28/us/hacker-s...,"$9,511.47","$9,561.59",+0.53%,"$11,969,796,019.00"
14,2019-07-26,"Want to Own a Warhol? Now, You Can Buy a Piece...",Several technology companies are packaging rar...,0.674236,https://www.nytimes.com/2019/07/26/your-money/...,"$9,799.51","$9,753.24",-0.47%,"$12,628,569,446.00"
15,2019-07-24,Strippers Are Doing It for Themselves,An industry organizes against decades of explo...,0.569638,https://www.nytimes.com/2019/07/24/style/strip...,"$9,729.01","$10,037.00",+3.17%,"$15,287,861,479.00"
16,2019-07-24,Who Cancels Lunch With Warren Buffett? A Chine...,Justin Sun denied reports that he had postpone...,0.462030,https://www.nytimes.com/2019/07/24/business/ch...,"$9,729.01","$10,037.00",+3.17%,"$15,287,861,479.00"
17,2019-07-23,‘South Side’ and ‘Sherman’s Showcase’: Two Fla...,One is an affectionately traditional sitcom; t...,0.609186,https://www.nytimes.com/2019/07/23/arts/televi...,"$10,098.35","$9,729.01",-3.66%,"$15,008,623,155.00"
18,2019-07-16,Tech Hearings: Congress Unites to Take Aim at ...,A series of hearings on Capitol Hill showed th...,0.978506,https://www.nytimes.com/2019/07/16/technology/...,"$10,387.16","$9,592.30",-7.65%,"$20,586,874,365.00"
19,2019-07-16,Facebook Cryptocurrency Plans Have a Problem: ...,Lawmakers raised broad concerns about the comp...,0.555394,https://www.nytimes.com/2019/07/16/technology/...,"$10,387.16","$9,592.30",-7.65%,"$20,586,874,365.00"
20,2019-07-15,Cryptocurrencies Pose National Security Threat...,The Treasury secretary raised concerns about c...,0.739741,https://www.nytimes.com/2019/07/15/us/politics...,"$10,445.74","$10,387.16",-0.56%,"$23,342,688,432.00"
21,2019-07-15,How to Stay Financially Stable When the World ...,"Trade wars, climate change and slowing economi...",0.757461,https://www.nytimes.com/2019/07/15/your-money/...,"$10,445.74","$10,387.16",-0.56%,"$23,342,688,432.00"
22,2019-07-12,DealBook Briefing: Why Are Stocks Still Rising?,Economic fears are climbing — but so are the m...,0.496954,https://www.nytimes.com/2019/07/12/business/de...,"$11,590.77","$11,443.92",-1.27%,"$23,968,073,000.00"
23,2019-07-12,Facebook’s Digital Money Could Mean Fabulous W...,The social network is planning a new cryptocur...,0.721003,https://www.nytimes.com/2019/07/12/business/fa...,"$11,590.77","$11,443.92",-1.27%,"$23,968,073,000.00"
24,2019-07-10,Fed Chair Raises ‘Serious Concerns’ About Face...,"Jerome Powell, the chair of the Federal Reserv...",0.569516,https://www.nytimes.com/2019/07/10/technology/...,"$12,651.89","$11,608.32",-8.25%,"$26,893,573,195.00"
25,2019-07-09,"To Save Her Abducted Daughter, This Heroine Ha...","“The Chain,” Adrian McKinty‘s existential thri...",0.614056,https://www.nytimes.com/2019/07/09/books/revie...,"$12,509.19","$12,651.89",+1.14%,"$24,620,535,985.00"
26,2019-07-09,"Fix Your Finances, Simply. Try the 7-Day Money...",Tackle a simple money task each day for a week...,0.481466,https://www.nytimes.com/2019/07/09/well/fix-yo...,"$12,509.19","$12,651.89",+1.14%,"$24,620,535,985.00"
27,2019-07-07,A City Paid a Hefty Ransom to Hackers. But Its...,"Weeks after Lake City, Fla., was hit by a cybe...",0.672367,https://www.nytimes.com/2019/07/07/us/florida-...,"$11,322.10","$11,784.80",+4.09%,"$17,513,443,476.00"
28,2019-07-06,Selling Your Private Information Is a Terrible...,We don’t allow people to sell their kidneys. W...,0.242600,https://www.nytimes.com/2019/07/05/opinion/hea...,"$11,425.48","$11,322.10",-0.90%,"$20,424,008,146.00"
29,2019-07-05,DealBook Briefing: Deutsche Bank’s Bloodlettin...,The embattled German lender’s board is expecte...,0.878920,https://www.nytimes.com/2019/07/05/business/de...,"$11,165.99","$11,425.48",+2.32%,"$22,471,262,211.00"
...,...,...,...,...,...,...,...,...,...
1477,2013-04-15,This Week in Small Business: Free Lunch?,A declining deficit? A global recession? Why s...,0.481750,https://boss.blogs.nytimes.com/2013/04/15/this...,NaN,NaN,NaN,NaN
1478,2013-04-15,The Antisocial Network,The fruitless search for dehumanized money.,0.458582,https://www.nytimes.com/2013/04/15/opinion/kru...,NaN,NaN,NaN,NaN
1479,2013-04-12,Adam Smith Hates Bitcoin,Blazing a high-tech path to the 17th century.,0.283808,https://krugman.blogs.nytimes.com/2013/04/12/a...,NaN,NaN,NaN,NaN
1480,2013-04-12,Week in Review: From Banes of Zuckerberg to Bi...,Never mind Facebook; the Winklevoss twins rule...,0.217626,https://dealbook.nytimes.com/2013/04/12/week-i...,NaN,NaN,NaN,NaN
1481,2013-04-12,JPMorgan Kicks Off Bank Earnings,JPMorgan Chase said on Friday that its first-q...,0.328187,https://dealbook.nytimes.com/2013/04/12/jpmorg...,NaN,NaN,NaN,NaN
1482,2013-04-12,Daily Report: Digital Money Is Gaining Champio...,Silicon Valley and Wall Street are taking note...,0.622317,https://bits.blogs.nytimes.com/2013/04/12/dail...,NaN,NaN,NaN,NaN
1483,2013-04-12,IHT Quick Read: April 12,Worries about the H7N9 bird flu; Russia bets o...,0.512486,https://rendezvous.blogs.nytimes.com/2013/04/1...,NaN,NaN,NaN,NaN
1484,2013-04-11,TimesCast: Bitcoin Has Real-World Investors,The Times’s Nathaniel Popper discusses Bitcoin...,0.512446,https://bits.blogs.nytimes.com/2013/04/11/time...,NaN,NaN,NaN,NaN
1485,2013-04-11,Bitcoin Has Real-World Investors,The Times’s Nathaniel Popper discusses Bitcoin...,0.512446,https://www.nytimes.com/video/business/1000000...,NaN,NaN,NaN,NaN
1486,2013-04-11,Never Mind Facebook; Winklevoss Twins Rule in ...,Silicon Valley and Wall Street are taking note...,0.351284,https://dealbook.nytimes.com/2013/04/11/as-big...,NaN,NaN,NaN,NaN
1487,2013-04-09,Today’s Scuttlebot: Texting on ‘Sherlock’ and ...,The technology reporters and editors of The Ne...,0.979059,https://bits.blogs.nytimes.com/2013/04/09/toda...,NaN,NaN,NaN,NaN
1488,2013-04-08,This Week in Small Business: Not Again!,The jobs report is a “punch in the gut.” Once ...,0.618546,https://boss.blogs.nytimes.com/2013/04/08/this...,NaN,NaN,NaN,NaN
1489,2013-04-08,"Bubble or No, This Virtual Currency Is a Lot o...","The bitcoin, a virtual currency created in 200...",0.326230,https://www.nytimes.com/2013/04/08/business/me...,NaN,NaN,NaN,NaN
1490,2013-04-03,"Today’s Scuttlebot: Anonymous vs. North Korea,...",The technology reporters and editors of The Ne...,0.682859,https://bits.blogs.nytimes.com/2013/04/03/toda...,NaN,NaN,NaN,NaN
1491,2013-03-27,Today’s Scuttlebot: New Directions in Start-Up...,The technology reporters and editors of The Ne...,0.727518,https://bits.blogs.nytimes.com/2013/03/27/toda...,NaN,NaN,NaN,NaN
1492,2013-03-22,"Today’s Scuttlebot: Netflix TV, and Bitcoins f...",The technology reporters and editors of The Ne...,0.680560,https://bits.blogs.nytimes.com/2013/03/22/toda...,NaN,NaN,NaN,NaN
1493,2013-03-13,Today’s Scuttlebot: Bitcoin Problem and Tracki...,The technology reporters and editors of The Ne...,0.482012,https://bits.blogs.nytimes.com/2013/03/12/toda...,NaN,NaN,NaN,NaN
1494,2012-11-16,Today’s Scuttlebot: EBay Twinkies and Obama’s ...,The technology reporters and editors of The Ne...,0.678295,https://bits.blogs.nytimes.com/2012/11/16/toda...,NaN,NaN,NaN,NaN
1495,2012-08-23,What’s Coming Out of Silicon Valley,Here is a rare insider look at the current cro...,0.665351,https://bits.blogs.nytimes.com/2012/08/23/what...,NaN,NaN,NaN,NaN
1496,2012-07-14,"And Now, ‘Occupy,’ the Camp",A summer camp that follows in the spirit of th...,0.503916,https://www.nytimes.com/2012/07/15/nyregion/an...,NaN,NaN,NaN,NaN
1497,2012-07-02,Doing Apps and Start-Ups While Still in High S...,"The Paly Entrepreneurs Club in Palo Alto, Cali...",0.630853,https://www.nytimes.com/2012/07/03/technology/...,NaN,NaN,NaN,NaN
1498,2012-05-14,"Today’s Scuttlebot: Virtual Robbery, and Track...",The technology reporters and editors of The Ne...,0.861305,https://bits.blogs.nytimes.com/2012/05/14/toda...,NaN,NaN,NaN,NaN
1499,2012-04-28,"The Post-Cash, Post-Credit-Card Economy","Your smartphone keeps track of where you are, ...",0.291873,https://www.nytimes.com/2012/04/29/sunday-revi...,NaN,NaN,NaN,NaN
1500,2012-03-28,Cybersecurity Researchers Team Up to Combat On...,"Two days before Microsoft, aided by United Sta...",0.891497,https://bits.blogs.nytimes.com/2012/03/28/cybe...,NaN,NaN,NaN,NaN
1501,2012-03-26,‘Good Wife’ Watch: Alicia Florrick v. the Patr...,Which injustice to Alicia was worse in Sunday ...,0.222362,https://artsbeat.blogs.nytimes.com/2012/03/25/...,NaN,NaN,NaN,NaN
1502,2012-01-16,"‘Good Wife’ Watch: Jason Biggs, Jim Cramer and...",Jason Biggs tries drama for a change on an epi...,0.322550,https://artsbeat.blogs.nytimes.com/2012/01/16/...,NaN,NaN,NaN,NaN
1503,2011-11-29,"Today’s Scuttlebot: Drones for Everyone, and B...",The technology reporters and editors of The Ne...,0.488838,https://bits.blogs.nytimes.com/2011/11/28/toda...,NaN,NaN,NaN,NaN
1504,2011-09-07,Golden Cyberfetters,"Digital, but still a barbarous relic.",0.663265,https://krugman.blogs.nytimes.com/2011/09/07/g...,NaN,NaN,NaN,NaN
1505,2011-07-03,Speed Bumps on the Road to Virtual Cash,The past few weeks have shown that a virtual c...,0.352042,https://www.nytimes.com/2011/07/04/business/me...,NaN,NaN,NaN,NaN
1506,2011-05-30,Some Faint Praise for Mr. Ballmer,David Einhorn’s critique of Steve Ballmer is o...,0.680989,https://www.nytimes.com/2011/05/30/business/ec...,NaN,NaN,NaN,NaN

In [15]:
trend_df = pd.read_csv('Google_Trends.csv')
trend_df = trend_df[:1961]
trend_df.rename(columns={"Unnamed:0": "date", "Category:All categories": })

      Unnamed: 0  Category: All categories
0     2014-07-01                      51.0
1     2014-07-02                      53.0
2     2014-07-03                      48.0
3     2014-07-04                      48.0
4     2014-07-05                      37.0
5     2014-07-06                      47.0
6     2014-07-07                      48.0
7     2014-07-08                      44.0
8     2014-07-09                      42.0
9     2014-07-10                      49.0
10    2014-07-11                      46.0
11    2014-07-12                      43.0
12    2014-07-13                      37.0
13    2014-07-14                      41.0
14    2014-07-15                      46.0
15    2014-07-16                      51.0
16    2014-07-17                      51.0
17    2014-07-18                      51.0
18    2014-07-19                      50.0
19    2014-07-20                      44.0
20    2014-07-21                      44.0
21    2014-07-22                      49.0
22    2014-07-23                      44.0
23    2014-07-24                      47.0
24    2014-07-25                      43.0
25    2014-07-26                      38.0
26    2014-07-27                      41.0
27    2014-07-28                      42.0
28    2014-07-29                      44.0
29    2014-07-30                      47.0
...          ...                       ...
1931  2019-07-15                      44.0
1932  2019-07-16                      44.0
1933  2019-07-17                      45.0
1934  2019-07-18                      43.0
1935  2019-07-19                      37.0
1936  2019-07-20                      31.0
1937  2019-07-21                      31.0
1938  2019-07-22                      33.0
1939  2019-07-23                      34.0
1940  2019-07-24                      35.0
1941  2019-07-25                      34.0
1942  2019-07-26                      31.0
1943  2019-07-27                      31.0
1944  2019-07-28                      29.0
1945  2019-07-29                      32.0
1946  2019-07-30                      31.0
1947  2019-07-31                      32.0
1948  2019-08-01                      31.0
1949  2019-08-02                      33.0
1950  2019-08-03                      30.0
1951  2019-08-04                      30.0
1952  2019-08-05                      44.0
1953  2019-08-06                      43.0
1954  2019-08-07                      39.0
1955  2019-08-08                      36.0
1956  2019-08-09                      33.0
1957  2019-08-10                      30.0
1958  2019-08-11                      29.0
1959  2019-08-12                      32.0
1960  2019-08-13                      32.0

[1961 rows x 2 columns]

In [8]:
# Save dataframe as CSV
merged_df.to_csv('BTC_Price_Sentiment.csv')

# Save dataframe as JSON
merged_df.to_json('BTC_Price_Sentiment.json')